services:
  qdrant:
    image: qdrant/qdrant:v1.9.2
    ports:
      - "6333:6333"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/readyz"]
      interval: 5s
      retries: 10
    volumes:
      - qdrant_storage:/qdrant/storage
  api:
    build: .
    depends_on:
      - qdrant
    environment:
      - CONFIG_PATH=configs/default.yaml
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=http://qdrant:6333
    ports:
      - "8000:8000"
    command: uvicorn src.search.api:app --host 0.0.0.0 --port 8000

volumes:
  qdrant_storage:


