services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - postgres
    environment:
      - CONFIG_PATH=configs/default.yaml
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VECTOR_DSN=postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - "8000:8000"
    command: uvicorn src.search.api:app --host 0.0.0.0 --port 8000

volumes:
  pg_data:


